# file: roles/docker_install/tasks/main.yml
---
- name: Gathering facts
  ansible.builtin.setup:
    gather_subset: min

- name: Installing dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
    state: present

- name: Adding GPG key for Docker apt repo
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding Docker apt repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Updating apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Installing Docker CE
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present

- name: Adding {{ target_user }} to the docker group
  ansible.builtin.user:
    name: '{{ target_user }}'
    groups: docker
    append: true
  notify: Restart Docker

- name: Creating /etc/docker/daemon.json
  ansible.builtin.copy:
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "storage-opts": [
          "overlay2.override_kernel_check=true"
        ]
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart docker

- name: Restarting Docker now
  ansible.builtin.meta: flush_handlers
...
