# file: roles/ipv6_disable/tasks/ubuntu24.yml
---
- name: Updating /etc/default/grub
  ansible.builtin.copy:
    src: grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
  notify: Update grub and reboot

- name: Removing ip6 lines from /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '{{ item }}'
    state: absent
    backup: true
  loop:
    - ip6
    - IPv6

- name: Disable IPv6 in /etc/sysctl.conf
  ansible.builtin.blockinfile:
    block: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
    path: /etc/sysctl.conf
    backup: true
  notify: IPV6 Load Changes

- name: Flushing handlers for immediate reboot
  ansible.builtin.meta: flush_handlers
...
# vim: filetype=ansible syntax=yaml.ansible
