# file: roles/docker_install/handlers/main.yml
---
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
    daemon_reload: true

- name: Docker reboot
  ansible.builtin.reboot:
...
